# Site settings
title: Website Style Guide Resources
description: A collaborative collection of resources for creating Front-End Style Guides and Pattern Libraries
baseurl: ""

# Build settings
markdown: kramdown

collections:
    resourcearticle:
        output: true
    resourcebook:
        output: true
    resourceexample:
        output: true
    resourceguide:
        output: true
    resourcepodcast:
        output: true
    resourcetalk:
        output: true
    resourcetool:
        output: true
    